#pragma once

#include <cstdint>

#include "TelemetryState.h"

/**
 * CRSF Telemetry
 *
 * Responsible for converting flight-controller telemetry
 * state into CRSF telemetry frames.
 *
 * Frame format:
 *
 * [Address]
 * [Length]
 * [Type]
 * [Payload]
 * [CRC]
 *
 * CRC is calculated over:
 *
 *     Type + Payload
 *
 * The generated frame is intended to be transmitted
 * from the flight controller to the ELRS receiver.
 */
class CrsfTelemetry
{
public:
    CrsfTelemetry();

    /**
     * Update telemetry scheduler.
     *
     * This function should be called periodically from
     * the telemetry task.
     *
     * When a telemetry packet is ready:
     *
     *     hasFrame() == true
     *
     * The caller should then transmit:
     *
     *     frame()
     *     frameSize()
     *
     * and call clearFrame().
     */
    void update(
        const TelemetryState &state,
        uint32_t nowMs);

    /**
     * Returns true when a complete telemetry frame
     * is ready for transmission.
     */
    bool hasFrame() const;

    /**
     * Returns pointer to the generated CRSF frame.
     */
    const uint8_t *frame() const;

    /**
     * Returns size of the generated CRSF frame.
     */
    uint8_t frameSize() const;

    /**
     * Clear the currently prepared frame.
     */
    void clearFrame();

private:
    // --------------------------------------------------------
    // Telemetry frame builders
    // --------------------------------------------------------

    bool buildBatteryFrame(
        const TelemetryState &state);

    bool buildGpsFrame(
        const TelemetryState &state);

    bool buildVarioFrame(
        const TelemetryState &state);

    bool buildAttitudeFrame(
        const TelemetryState &state);

    bool buildFlightModeFrame(
        const TelemetryState &state);

    // --------------------------------------------------------
    // Serialization helpers
    // --------------------------------------------------------

    void writeU16(
        uint8_t *buffer,
        uint16_t value);

    void writeI16(
        uint8_t *buffer,
        int16_t value);

    void writeU24(
        uint8_t *buffer,
        uint32_t value);

    void writeI32(
        uint8_t *buffer,
        int32_t value);

    void writeU32(
        uint8_t *buffer,
        uint32_t value);

    // --------------------------------------------------------
    // CRSF CRC
    // --------------------------------------------------------

    uint8_t calculateCrc(
        const uint8_t *data,
        uint8_t length) const;

    // --------------------------------------------------------
    // Frame construction
    // --------------------------------------------------------

    /**
     * Start a CRSF telemetry frame.
     *
     * Creates:
     *
     * [address]
     * [length]
     * [type]
     *
     * Payload and CRC are added by the individual
     * frame builder.
     */
    bool beginFrame(
        uint8_t type,
        uint8_t payloadSize);

private:
    // --------------------------------------------------------
    // Frame buffer
    // --------------------------------------------------------

    static constexpr uint8_t BufferSize = 64;

    uint8_t _buffer[BufferSize]{};

    uint8_t _frameSize = 0;

    bool _hasFrame = false;

    // --------------------------------------------------------
    // CRSF addresses
    // --------------------------------------------------------

    /**
     * CRSF receiver address.
     *
     * Telemetry generated by the FC is sent toward
     * the receiver.
     */
    static constexpr uint8_t AddressReceiver = 0xEC;

    // --------------------------------------------------------
    // CRSF telemetry packet types
    // --------------------------------------------------------

    /**
     * GPS telemetry
     */
    static constexpr uint8_t TypeGps = 0x02;

    /**
     * Variometer telemetry
     */
    static constexpr uint8_t TypeVario = 0x07;

    /**
     * Battery sensor telemetry
     */
    static constexpr uint8_t TypeBattery = 0x08;

    /**
     * Attitude telemetry
     */
    static constexpr uint8_t TypeAttitude = 0x1E;

    /**
     * Flight mode telemetry
     */
    static constexpr uint8_t TypeFlightMode = 0x21;

    // --------------------------------------------------------
    // CRSF telemetry payload sizes
    // --------------------------------------------------------

    /**
     * GPS payload:
     *
     * latitude       4 bytes
     * longitude      4 bytes
     * ground speed   2 bytes
     * heading        2 bytes
     * altitude       2 bytes
     * satellites     1 byte
     *
     * Total = 15 bytes
     */
    static constexpr uint8_t GpsPayloadSize = 15;

    /**
     * Variometer payload:
     *
     * vertical speed = 2 bytes
     */
    static constexpr uint8_t VarioPayloadSize = 2;

    /**
     * Battery payload:
     *
     * voltage       2 bytes
     * current       2 bytes
     * capacity      3 bytes
     * remaining     1 byte
     *
     * Total = 8 bytes
     */
    static constexpr uint8_t BatteryPayloadSize = 8;

    /**
     * Attitude payload:
     *
     * roll       2 bytes
     * pitch      2 bytes
     * yaw        2 bytes
     *
     * Total = 6 bytes
     */
    static constexpr uint8_t AttitudePayloadSize = 6;

    // --------------------------------------------------------
    // Flight mode
    // --------------------------------------------------------

    /**
     * Maximum flight-mode string size.
     *
     * CRSF flight mode telemetry is a text payload,
     * not a numeric mode ID.
     */
    static constexpr uint8_t MaxFlightModeLength = 16;

    /**
     * Maximum flight-mode payload:
     *
     * Type + mode string
     */
    static constexpr uint8_t FlightModePayloadSize =
        MaxFlightModeLength;

    // --------------------------------------------------------
    // Telemetry scheduling
    // --------------------------------------------------------

    /**
     * Battery telemetry interval.
     */
    static constexpr uint32_t BatteryIntervalMs = 100;

    /**
     * GPS telemetry interval.
     */
    static constexpr uint32_t GpsIntervalMs = 250;

    /**
     * Variometer telemetry interval.
     */
    static constexpr uint32_t VarioIntervalMs = 100;

    /**
     * Attitude telemetry interval.
     */
    static constexpr uint32_t AttitudeIntervalMs = 100;

    /**
     * Flight mode telemetry interval.
     */
    static constexpr uint32_t FlightModeIntervalMs = 500;

    // --------------------------------------------------------
    // Scheduler state
    // --------------------------------------------------------

    uint32_t _lastBatteryMs = 0;

    uint32_t _lastGpsMs = 0;

    uint32_t _lastVarioMs = 0;

    uint32_t _lastAttitudeMs = 0;

    uint32_t _lastFlightModeMs = 0;
};